autogluon/autogluon-cloud

- .gitignore
- NOTICE
- setup.py
- src/autogluon/cloud/version.py
* Updated setup.py with necessary util functions, and modified them to adapt repo change. Installation has been tested locally.
* Updated dependency version ranges
> Update setup.py to adapt repo change

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
* Reused `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` from `autogluon` with modification on `CONTRIBUTING.md` to apply to the cloud module
> Contributing and Code of Conduct

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/test-cloud/action.yml
- .github/workflow_scripts/cloud_lint_check.sh
- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_cloud.sh
- .github/workflows/continuous_integration.yml
- pyproject.toml
- setup.py
* Move cloud CI
* Removed path filter in workflow and removed some unnecessary prefix of `cloud` in the CI
* Updated scripts to adopt new repo structure
* Style changes of setup.py
> Migrate cloud CI

- src/autogluon/cloud/predictor/cloud_predictor.py
* Mistake were made during migration. Lost two PRs, this will be the first one
> Reapply https://github.com/autogluon/autogluon/pull/2533

- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/scripts/image_serve.py
- src/autogluon/cloud/scripts/multimodal_serve.py
- src/autogluon/cloud/scripts/tabular_serve.py
- src/autogluon/cloud/scripts/text_serve.py
- tests/conftest.py
- tests/unittests/general/test_full_functionality.py
- tests/unittests/image/test_image.py
- tests/unittests/multimodal/test_multimodal.py
- tests/unittests/tabular/test_tabular.py
- tests/unittests/text/test_text.py
* Support output content type as list
* Disable debug mode
* Fix test using cpu image only
> Support output content type as list

- .github/workflows/pythonpublish.yml
> Nightly release

- tests/unittests/general/test_full_functionality.py
- tests/unittests/general/test_prepare_data.py
- tests/unittests/image/test_image.py
- tests/unittests/multimodal/test_multimodal.py
- tests/unittests/tabular/test_tabular.py
- tests/unittests/text/test_text.py
* Previously tempdir was created but never being used... Causing issue occasionally when tests that zip images running in parallel
> Fix tempdir

- .github/workflow_scripts/build_doc.sh
- .github/workflows/continuous_integration.yml
* Add doc check to speed up CI when only doc changes
* Fixed a minor issue when in build_doc.sh
**Cancelled CI for PR to save compute**
> [CI] Add doc check

- docs/tutorials/autogluon-cloud.md
> [Doc] Tutorial

- src/autogluon/cloud/predictor/cloud_predictor.py
- tests/unittests/tabular/test_tabular.py
* Allow users to pass args to control the behavior of `load` call underneath `to_local_predictor`
> Add kwargs to `to_local_predictor`

- src/autogluon/cloud/predictor/cloud_predictor.py
* CI failure on lint stage possibly because of lint update. Fix according to the suggestion
> Lint update

- .github/workflows/pypi_release.yml
* Modified based on the workflow being used by main AG repo
> pypi release workflow

- README.md
- docs/index.rst
- docs/tutorials/autogluon-cloud.md
> Fix tutorial

- docs/config.ini
- docs/index.rst
- docs/versions.rst
- setup.py
> Update to 0.1.1

- .github/workflows/continuous_integration.yml
> Update CI to test 0.6.2 container

- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/utils/ag_sagemaker.py
https://github.com/autogluon/autogluon-cloud/issues/39
> Server worker and deploy volume

- .github/workflows/continuous_integration.yml
> Add cluster role to CI

- src/autogluon/cloud/job/sagemaker_job.py
- src/autogluon/cloud/utils/ag_sagemaker.py
- src/autogluon/cloud/utils/sagemaker_iam.py
- tests/conftest.py
https://github.com/autogluon/autogluon-cloud/issues/32
* Fix attach job failure
* Add unit test and additional permission required
> Fix attach_job

- setup.py
> Update dependency ranges

- docs/README.md
- docs/index.md
* Add MultiModal and TimeSeries quick example
* Add build doc locally instruction
> Add MultiModal and TimeSeries quick example

- src/autogluon/cloud/predictor/cloud_predictor.py
> Add better warning msg for `to_local_predictor`

- docs/index.md
> Add versions to website

- docs/index.md
> Add versions to stable

- README.md
- docs/conf.py
- docs/versions.rst
- setup.py
* Noticed that `versions.rst` is not being added to the new website. Will have a follow-up PR so that it's easier to be cherry picked into stable branch
> Update to 0.2.1

- .github/workflow_scripts/test_cloud.sh
- setup.py
- src/autogluon/cloud/backend/backend.py
- src/autogluon/cloud/backend/ray_backend.py
- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/backend/tabular_sagemaker_backend.py
- src/autogluon/cloud/scripts/ray_scripts/train.py
- src/autogluon/cloud/scripts/sagemaker_scripts/train.py
- tests/unittests/cluster/test_distributed_training.py
- tests/unittests/tabular/test_tabular.py
* Enable user to include objects in `ag_init_args` and `ag_fit_args` by passing pickle instead of yaml
> Enable pickle

- src/autogluon/cloud/scripts/sagemaker_scripts/tabular_serve.py
> Persist models

- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/predictor/cloud_predictor.py
* Allow user to set volume size when deploy. Also add check for gpu instances as volume size is not supported
> Add volume deploy option

- .github/workflow_scripts/test_cloud.sh
- src/autogluon/cloud/backend/backend.py
- src/autogluon/cloud/backend/ray_backend.py
- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- tests/unittests/general/test_full_functionality.py
https://github.com/autogluon/autogluon-cloud/issues/83
> Optional cloud output path

- src/autogluon/cloud/predictor/cloud_predictor.py
https://github.com/autogluon/autogluon-cloud/issues/61
> Add predictor_path to `to_local_predictor`

- src/autogluon/cloud/backend/multimodal_sagemaker_backend.py
- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/backend/timeseries_sagemaker_backend.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/predictor/timeseries_cloud_predictor.py
- src/autogluon/cloud/scripts/sagemaker_scripts/multimodal_serve.py
- src/autogluon/cloud/scripts/sagemaker_scripts/tabular_serve.py
- src/autogluon/cloud/scripts/sagemaker_scripts/timeseries_serve.py
- src/autogluon/cloud/utils/ag_sagemaker.py
- src/autogluon/cloud/utils/serializers.py
- tests/conftest.py
- tests/unittests/general/test_full_functionality.py
https://github.com/autogluon/autogluon-cloud/issues/70
* Added custom serialization and deserialization logic to embed extra arguments. This allow user to pass additional arguments to real time prediction.
> Add support for extra arguments for real time prediction

- src/autogluon/cloud/scripts/sagemaker_scripts/tabular_serve.py
> Batch inference no header

- setup.py
- src/autogluon/cloud/endpoint/sagemaker_endpoint.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/scripts/sagemaker_scripts/multimodal_serve.py
- src/autogluon/cloud/utils/ag_sagemaker.py
- tests/unittests/multimodal/test_multimodal.py
update dependency version to match autogluon 1.0.0 requirements
> update dependency version to match autogluon 1.0.0 requirements

- README.md
- docs/conf.py
- docs/whats_new/v0.3.0.md
- pyproject.toml
- setup.py
* Add release notes for v0.3.0
* Update version
* Update Readme
Testing:
* Tested pre-release version on mac and linux. Training, real time inference and batch inference works fine for tabular
> Release prep for v0.3.0

- docs/index.md
> fix docs for quick start guide

- docs/conf.py
- docs/versions.rst
- docs/whats_new/v0.3.1.md
- setup.py
> [Bug fix] release 0.3.1 for critical bug fixes

- setup.py
> Added ray config to distribution

- docs/index.md
- docs/tutorials/autogluon-cloud.md
- Fix several typos that raise SyntaxErrors when copy-pasting code from the tutorial
- Add detailed instructions on adding IAM roles / policies to the quickstart tutorial
> Minor fixes to the documentation

- .github/workflows/continuous_integration.yml
> [Fix] Fix workflow checkout actions

- .github/workflows/continuous_integration.yml
> [Fix] Workflow checkout

- .github/workflows/continuous_integration.yml
> [Fix] Fix for branch 0.1.0

- .github/workflows/continuous_integration.yml
> [Fix] Fix 0.2.0 branch

- .github/workflows/continuous_integration.yml
> [Fix] Fix 0.3.0 branch

- .github/workflows/continuous_integration.yml
> [Fix] Fix stable branch

- .github/workflows/continuous_integration.yml
- setup.py
> Update AG version in test to align with docker image dependencies

- docs/conf.py
- docs/versions.rst
> 0.4.1 release

- setup.py
> update setup version

- docs/conf.py
- docs/versions.rst
- setup.py
> Release 0.4.2

- .github/workflows/continuous_integration.yml
https://github.com/autogluon/autogluon-cloud/issues/174
> Disable cluster test on source
