autogluon/autogluon-cloud

- src/autogluon/cloud/scripts/multimodal_serve.py
Since MultiModalPredictor now supports image bytearray as an input, we no longer need to save image to disk to parse `image_path` to the model during cloud deployment.
> Reapply https://github.com/autogluon/autogluon/pull/2495/

- .gitignore
- src/autogluon/cloud/utils/ag_sagemaker.py
Disable Python output buffering for endpoint logging. See logging emitted after this change
```
2022-12-21T00:57:37,730 [WARN ] W-model-9-stderr com.amazonaws.ml.mms.wlm.WorkerLifeCycle - /usr/local/lib/python3.8/dist-packages/autogluon/multimodal/utils/environment.py:54: UserWarning: Using the detected GPU number 0, smaller than the GPU number 1 in the config.
```
> Disable Python output buffering for endpoint logging

- .github/actions/test-cloud/action.yml
- .github/workflows/continuous_integration.yml
- setup.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- tests/unittests/general/test_full_functionality.py
- tests/unittests/image/test_image.py
- tests/unittests/multimodal/test_multimodal.py
- tests/unittests/tabular/test_tabular.py
- tests/unittests/text/test_text.py
* Add CI to test 0.6.1 framework.
* Remove test of TextCloudPredictor as it is basically the same as tabular in terms of cloud logic.
* Set lower bound for sagmaker sdk to support 0.6.1 container
**Cancel PR CI run to save resource intentionally**
> [CI]Add test 0.6.1

- docs/tutorials/autogluon-cloud.md
- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/predictor/image_cloud_predictor.py
- src/autogluon/cloud/predictor/multimodal_cloud_predictor.py
- src/autogluon/cloud/utils/__init__.py
- src/autogluon/cloud/utils/utils.py
* Add flags to enable user get batch transform results directly in a `predict` call
* Removed the uuid renaming as the folder has already been generated based on job_name. No need to rename file. And with uuid you cannot log it as it triggers security concern.
> Download batch transform results in predict call

- src/autogluon/cloud/job/sagemaker_job.py
- src/autogluon/cloud/predictor/cloud_predictor.py
* Noticed cloud predictor was uploading training script to a different s3 path than the rest of the utils. This PR fix it.
* Have ran a local test and confirmed code has been uploaded to the correct s3 path.
> Code location

- src/autogluon/cloud/data/format_converter.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/predictor/multimodal_cloud_predictor.py
- src/autogluon/cloud/predictor/tabular_cloud_predictor.py
- src/autogluon/cloud/scripts/script_manager.py
- src/autogluon/cloud/scripts/tabular_serve.py
- src/autogluon/cloud/utils/deserializers.py
- tests/conftest.py
> Apply new black

- docs/index.rst
This change updates the external links on the landing page from Markdown syntax to [rst sytax](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages). The current links are not being rendered correctly on the website.
While I was here, I updated a few words as well.
> Fix external rst links on landing page

- .github/workflow_scripts/test_cluster.sh
- .github/workflows/continuous_integration.yml
* Add cluster CI. This CI hasn't incorporate necessary IAM role setup for cluster yet. Now mainly for enabling cluster config testing
> Add cluster ci

- src/autogluon/cloud/predictor/cloud_predictor.py
* Logger not logging after backend extraction because file being moved around. CloudPredictor will now configure root `autogluon.cloud` logger instead.
> Fix logger

- docs/tutorials/autogluon-cloud.md
The `predictor_init_args` dict is being incorrectly used to set the `predictor_fit_args` in the `autogluon-cloud` tutorial.
> predictor fit args tutorial fix

- tests/unittests/cluster/test_ray_cluster.py
- tests/unittests/general/test_general.py
* Generate permission being moved to backend. No need to test in predictor anymore
* Disable ray job remote cluster test temporarily as it fails randomly. Need to investigate more. Local test is still enabled
> Fix general unit test

- docs/ReleaseInstructions.md
* Added release instruction based on AG release instruction.
> Add release instruction

- .github/workflows/pythonpublish.yml
* Nightly release not being ran because ubuntu-18.04 is deprecated on github action
> Fix nightly release

- docs/tutorials/autogluon-cloud.md
- src/autogluon/cloud/backend/backend_factory.py
- src/autogluon/cloud/backend/ray_aws_backend.py
- src/autogluon/cloud/backend/ray_backend.py
- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/cluster/ray_aws_cluster_manager.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/predictor/multimodal_cloud_predictor.py
- src/autogluon/cloud/predictor/tabular_cloud_predictor.py
- src/autogluon/cloud/predictor/timeseries_cloud_predictor.py
- tests/unittests/general/test_general.py
https://github.com/autogluon/autogluon-cloud/issues/82
After this change, users should be able to call `generate_default_permission` as a static method towards any `CloudPredictor`
> Improve permission

- CONTRIBUTING.md
- setup.py
closes https://github.com/autogluon/autogluon-cloud/issues/90
* Set pyyaml to ~=6.0
* readme update for correct python major versions. 
> pyyaml 6.0

- docs/index.md
- src/autogluon/cloud/predictor/timeseries_cloud_predictor.py
- tests/unittests/timeseries/test_timeseries.py
- Provide default values for `id_column` and `timestamp_column` in `TimeSeriesCloudPredictor.fit()`.
- Use values of `id_column`, `timestamp_column` and `target` provided during `fit()` when calling `predict()` and `predict_real_time()`.
- Now `predict()` and `predict_real_time()` method do not accept `id_column` and `timestamp_column` arguments, so it's a breaking change.
> Simplify TimeSeriesCloudPredictor API

- docs/conf.py
- docs/versions.rst
- docs/whats_new/v0.4.0.md
> 0.4.0 release

- src/autogluon/cloud/scripts/sagemaker_scripts/timeseries_serve.py
`TimeSeriesPredictor.persist()` API will be added with v1.1 and is crucial for serving pretrained models in production. This PR introduces this call to the time series SM serve script.
> [timeseries] add persist call to timeseries serve script

- src/autogluon/cloud/backend/ray_aws_backend.py
- src/autogluon/cloud/utils/ag_sagemaker.py
- src/autogluon/cloud/utils/iam.py
Addressed two issues:
1. https://github.com/autogluon/autogluon-cloud/issues/130
2. Only create policy when not already existed due to restrictions on "Permission Mutation Policies" and we will lose policy that allows us to create new roles.
> add model_reference_arn in signature

- .github/workflows/continuous_integration.yml
- src/autogluon/cloud/default_cluster_configs/ray_aws_default_cluster_config.yaml
- tests/unittests/cluster/test_distributed_training.py
- tests/unittests/image/test_image.py
This PR fixes a few bugs in CI.
> Fix ci image versions

- .gitignore
- src/autogluon/cloud/backend/backend.py
- src/autogluon/cloud/backend/sagemaker_backend.py
- src/autogluon/cloud/predictor/cloud_predictor.py
- src/autogluon/cloud/scripts/sagemaker_scripts/tabular_serve.py
This PR fixes the issue where batch transform jobs fail due to column misalignment when the input CSV file is partitioned into multiple records. The problem arises because headers from different partitions are not handled properly, leading to misaligned columns and prediction failures during inference.
**Changes:**
- Added logic to align columns across partitions by ensuring headers are managed correctly.
- Introduced `_read_with_fallback` and `_align_columns` helper functions to handle column alignment.
- Updated `transform_fn` in `tabular_serve.py` to use these helper functions.
**Limitations:**
- This fix currently only works for the tabular predictor. Support for multimodal and timeseries predictors depends on the implementation of `original_features`, which can be tracked in [issue …
> Fix batch transform issue for tabular predictor with multiple partitions

- .github/dependabot.yml
- .github/workflows/codeql.yml
- .github/workflows/continuous_integration.yml
- .github/workflows/pypi_release.yml
- .github/workflows/pythonpublish.yml
- Bump actions/checkout to v4 in various workflows
- Bump aws-actions/configure-aws-credentials to v2
- Bump peter-evans/create-or-update-comment to v4
- Update dependabot.yml to include pip and GitHub Actions ecosystems
> Update GitHub Actions and Dependabot configurations

- .github/workflows/codeql.yml
- Exclude Dependabot branches from triggering on push events
- Ensure CodeQL analysis runs on pull_request events for Dependabot
> Fix CodeQL workflow permissions for Dependabot branches

- .github/workflows/continuous_integration.yml
> fix permission check in CICD

- src/autogluon/cloud/cluster/ray_aws_cluster_config_generator.py
- src/autogluon/cloud/utils/aws_utils.py
- tests/unittests/cluster/test_cluster_config_generator.py
Use the latest AMI for cloud cluster test.
> Use latest AMI for cluster

- docs/requirements_doc.txt
- pyproject.toml
- setup.cfg
- setup.py
- src/autogluon/cloud/utils/dlc_utils.py
> Support py312
